### PR TITLE
New rr

### PR DESCRIPTION
**Pull request by geekyme**
- update to react v1.0.0-rc1
- refactored data fetching approach and use react-resolver in favor over our fireRouteAction. This is because transitionHooks is too difficult to manage on the new RR and react-resolver provides a declarative api over data requirement needs.

### CODE REVIEW

**Comment by geekyme** [comment]
oh nvm, this approach really isn't ready yet, a few problems: 
- no way to detect isTransitioning to display a loading screen
- browser back button appears to be broken.

**Comment by amorino** [comment]
If I want to help with something, should I work from this branch?

**Comment by geekyme** [comment]
Oh this is an experimental branch so best to make your own branch off mine.

**Comment by gpbl** [comment]
Hi @geekyme sorry for the delayed responses... i'm back into the project 🎉 
I'd like to understand the state of this feature from scratch, so I'm going to start my own branch with react-router so I can have a fresh look on it. Then I hope we can discuss better about the solutions we've found.

**Comment by geekyme** [comment]
Yo welcome back @gpbl, ok so the state of this branch is still not ready to be integrated into master. 

Problems encountered: 
- no ability to fire route actions anymore to get data required for photo page. 
- I've instead relied on react-resolver to fetch data.
- at the moment pressing back button on the browser will not bring u to previous route. No idea why. Perhaps it has something to do with how I register the hook on history to rerender the router. This is an approach I gleaned from a few others but I don't think this is the best approach.

Feel free to rework this branch to make the following work:
- integration with react-router@1.0.0-rc1
- fetching data before loading a route a.k.a route actions
- putting router state into the store (redux-router has problems, see their issue list)

**Comment by gpbl** [comment]
@amorino thanks for dropping in 🎁 The current state of the app makes some assumptions you may find hard to understand without knowing the history behind them. Feel free to start your own branch and try your ideas, but remember we could apply some big refactoring before we get to an usable release. I've opened a [gitter room](https://gitter.im/gpbl/redux500) for the repo to stay in contact in a better way!

**Comment by gpbl** [comment]
OK @geekyme thanks please keep this branch, because I need it for reference :-)

**Comment by geekyme** [comment]
Got it :thumbsup:

**Pull request closed without merging**
