### PR TITLE
asynchronous asset loading \m/

### PR DESCRIPTION
**Pull request by geekyme**
- bare minimum implementation to dynamically load assets for the PhotoPage and FeaturedPage

- we can now add the components and style and see the benefits of this approach!

### CODE REVIEW

**Comment by geekyme** [comment]
I didn't modify the readme here because I want to document the async asset loading only after i have integrated full styling and the components from isomorphic500. can't wait to see how it will work.

**Comment by gpbl** [comment]
Thanks @geekyme, nice job! I believe the router is a part that requires some effort to understand it.

I've reviewed a bit the code (mainly naming) in the hope to help others to understand it better. 
In the README we can explain it better. Maybe we can do something more (e.g. organizing the files in same subdirs), so if you have some fresh ideas...

**Comment by geekyme** [comment]
yeah i actually considered creating a subfolder for routes, to store all the PhotoRoute, FeaturedRoute, etc. But not sure what you think. 

I think the problem with the router part is because react-router does not provide a lot of documentation on how to use Router.run, along with transition hooks.

**Comment by gpbl** [comment]
I tries as well to place them in a subdir ... Not convinced. Let see this later? Btw is `getComponent` a the react-router interface? I guess I should read again the docs :)

**Comment by geekyme** [comment]
yes its a react-router interface. manual way of handling component fetching. you can read about it here but the docs does not go in depth about it :S http://rackt.github.io/react-router/tags/v1.0.0-beta3.html#Advanced Usage

**Comment by geekyme** [comment]
Anyway ready to merge I think.

**Pull request merged**
